"""VL53L0X register constants with semantic names."""

IDENTIFICATION_MODEL_ID = 0xC0
IDENTIFICATION_REVISION_ID = 0xC2

SYSRANGE_START = 0x00
SYSTEM_SEQUENCE_CONFIG = 0x01
SYSTEM_RANGE_CONFIG = 0x09
SYSTEM_INTERMEASUREMENT_PERIOD = 0x04
SYSTEM_INTERRUPT_CONFIG_GPIO = 0x0A
SYSTEM_INTERRUPT_CLEAR = 0x0B
SYSTEM_THRESH_HIGH = 0x0C
SYSTEM_THRESH_LOW = 0x0E

RESULT_INTERRUPT_STATUS = 0x13
RESULT_RANGE_STATUS = 0x14

SOFT_RESET_GO2_SOFT_RESET_N = 0xBF
FIRMWARE_BOOT_STATUS = 0x01

GPIO_HV_MUX_ACTIVE_HIGH = 0x84

MSRC_CONFIG_CONTROL = 0x60
MSRC_CONFIG_TIMEOUT_MACROP = 0x46
FINAL_RANGE_CFG_MIN_COUNT_RATE_RTN_LIMIT = 0x44

GLOBAL_CFG_SPAD_ENABLES_REF_0 = 0xB0
GLOBAL_CFG_REF_EN_START_SELECT = 0xB6
DYN_SPAD_REF_EN_START_OFFSET = 0x4F
DYN_SPAD_NUM_REQUESTED_REF_SPAD = 0x4E

PRE_RANGE_CONFIG_VCSEL_PERIOD = 0x50
PRE_RANGE_CONFIG_TIMEOUT_MACROP_HI = 0x51
FINAL_RANGE_CONFIG_VCSEL_PERIOD = 0x70
FINAL_RANGE_CONFIG_TIMEOUT_MACROP_HI = 0x71

VHV_CFG_PAD_SCL_SDA_EXTSUP_HV = 0x89
ALGO_PART_TO_PART_RANGE_OFFSET = 0x28
OSC_CALIBRATE_VAL = 0xF8

I2C_STANDARD_MODE = 0x88
I2C_SLAVE_DEVICE_ADDRESS = 0x8A
POWER_MGMT_GO1_POWER_FORCE = 0x80

INTERRUPT_STATUS_MASK = 0x07
GPIO_INTERRUPT_CONFIG = 0x04
SPAD_COUNT_MASK = 0x7F
SPAD_APERTURE_BIT = 0x80
SPAD_START_INDEX_APERTURE = 12
SPAD_MAP_BITS_PER_BYTE = 8
SPAD_TOTAL_COUNT = 48
SPAD_NUM_REQUESTED_REF = 0x2C
CALIBRATION_VHV_INIT = 0x40
TIMEOUT_LIMIT = 2.0
SIGNAL_RATE_LIMIT_FIXED = 32
